[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "test-contract"

[dependencies]
src20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.3.0" }
token = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.15.0" }